alias -- 'la'='eza -a'
alias -- 'll'='eza -l'
alias -- 'lla'='eza -la'
alias -- 'ls'='eza'
alias -- 'lt'='eza --tree'
alias -- 'tree'='eza --tree'
alias -- 'v'='nvim'
alias -- 'conflicts'='git diff --name-only --diff-filter=U'
alias -- 'ws'='cd ~/workspace'
