config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  instignore:
    - "*/.git"
variables:
  git_email: sebastian.schleemilch@posteo.net
actions:
  post:
    batcache: bat cache --build
    link_zshenv: ln -s -f ~/.config/zsh/.zshenv ~/.zshenv
dotfiles:
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
  d_tmux_tpm:
    src: config/tpm
    dst: ~/.tmux/plugins/tpm
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_git:
    src: config/git
    dst: ~/.config/git
  d_k9s:
    src: config/k9s
    dst: ~/.config/k9s
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_oh_my_posh:
    src: config/oh-my-posh
    dst: ~/.config/oh-my-posh
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_bat:
    src: config/bat
    dst: ~/.config/bat
    actions:
      - batcache
  d_btop:
    src: config/btop
    dst: ~/.config/btop
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    actions:
      - link_zshenv
    upignore:
      - "*/.zcompdump"
      - "*/.zhistory"
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_tofi:
    src: config/tofi
    dst: ~/.config/tofi
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_swaync:
    src: config/swaync
    dst: ~/.config/swaync
  f_face:
    src: config/face.png
    dst: ~/.face.png
  d_wallpaper:
    src: config/wallpaper
    dst: ~/wallpaper

profiles:
  cli:
    dotfiles:
      - d_tmux
      - d_tmux_tpm
      - d_git
      - d_k9s
      - d_lazygit
      - d_oh_my_posh
      - d_nvim
      - d_bat
      - d_btop
      - d_zsh
  desora:
    dotfiles:
      - d_alacritty
      - d_wallpaper
      - f_face
    include:
      - cli
  lapora:
    dotfiles:
      - d_alacritty
      - d_wallpaper
      - f_face
    include:
      - cli
  work:
    dotfiles:
      - d_alacritty
    include:
      - cli
    variables:
      git_email: sebastian.schleemilch@bmw.de
      proxy: 127.0.0.1:3128
