config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_btop:
    src: config/btop
    dst: ~/.config/btop
profiles:
  generic:
    dotfiles:
    - ALL
