config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_btop:
    src: config/btop
    dst: ~/.config/btop
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_tofi:
    src: config/tofi
    dst: ~/.config/tofi
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst

profiles:
  wsl:
    dotfiles:
    - f_tmux.conf
    - d_nvim
    - d_bat
    - d_btop
    - d_zsh
  baptop:
    dotfiles:
    - ALL
    variables:
      wifi: wlp1s0
      hwmon: 5
  barchtop:
    dotfiles:
    - ALL
    variables:
      wifi: wlp0s20f3
      hwmon: 4
