config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
actions:
  post:
    batcache: bat cache --build
    init_tpm: source ~/.config/zsh/scripts.zsh && init_tpm
dotfiles:
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
    actions:
    - init_tpm
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_git:
    src: config/git
    dst: ~/.config/git
  d_k9s:
    src: config/k9s
    dst: ~/.config/k9s
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_oh_my_posh:
    src: config/oh-my-posh
    dst: ~/.config/oh-my-posh
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_bat:
    src: config/bat
    dst: ~/.config/bat
    actions:
    - batcache
  d_btop:
    src: config/btop
    dst: ~/.config/btop
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    instignore:
    - "*/.git"
    upignore:
    - "*/.zcompdump"
    - "*/.zhistory"
  d_fsh:
    src: config/fsh
    dst: ~/.config/fsh
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_tofi:
    src: config/tofi
    dst: ~/.config/tofi
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_swaync:
    src: config/swaync
    dst: ~/.config/swaync

profiles:
  wsl:
    dotfiles:
    - d_tmux
    - d_git
    - d_k9s
    - d_lazygit
    - d_oh_my_posh
    - d_nvim
    - d_bat
    - d_btop
    - d_zsh
    - d_fsh
  desora:
    dotfiles:
    - d_zsh
    - d_fsh
    - d_oh_my_posh
    - d_alacritty
    - d_git
    - d_nvim
    - d_bat
    - d_tmux
    - d_btop
    - d_k9s
    - d_lazygit
