#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
VENV=$SCRIPT_DIR/.venv

if ! [ -d $VENV ]; then
    python -m venv $VENV
    source $VENV/bin/activate
    pip install requests
else
    source $VENV/bin/activate
fi

python $SCRIPT_DIR/weather.py
