#!/usr/bin/env bash

# Original script by @speltriao on GitHub
# https://github.com/speltriao/Pacman-Update-for-GNOME-Shell

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
    exit 0
fi
# Calculate updates for each service
AUR=$(paru -Qua | wc -l)
OFFICIAL=$(checkupdates | wc -l)

if [ "$1" = "update" ]; then
    alacritty --title Update -e paru
fi

if [ "$1" = "" ]; then
    COUNT=$((OFFICIAL+AUR))
    CLASS="warning"
    if [ "$COUNT" = "0" ]; then
        CLASS="ok"
    fi
    echo "{\"text\": \" $COUNT\", \"tooltip\": \"OFFICIAL: $OFFICIAL, AUR: $AUR\", \"class\": \"$CLASS\"}"
    exit 0
fi

