## Font configuration
font:
  # Normal (roman) font face
  normal:
    family: MesloLGS NF
    style: Regular

  # Bold font face
  bold:
    family: MesloLGS NF
    style: Bold

  # Italic font face
  italic:
    family: MesloLGS NF
    style: Italic

  # Bold italic font face
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic

  # Point size
  size: 14

  # Offset
  offset:
    x: 0
    y: 0

  # Glyph offset
  #glyph_offset:
  #  x: 0
  #  y: 0