format = "[-](surface2)$os$username$directory$git_branch$git_state$git_status$fill$direnv$nodejs$golang$rust$python$status$jobs$time[](surface2)$line_break$character"
palette = "catppuccin_macchiato"
[directory]
format = "[](fg:blue)[ $path](bold bg:blue fg:surface0)[](fg:blue)[-](surface2)"

[direnv]
allowed_msg = ""
denied_msg = ""
disabled = false
format = "[](fg:teal)[$symbol$loaded/$allowed](bold bg:teal fg:surface0)[](fg:teal)[-](surface2)"
loaded_msg = ""
not_allowed_msg = ""
symbol = " "

[fill]
disabled = false
style = "surface2"
symbol = "-"

[git_branch]
format = "[](fg:peach)[ $branch](bold bg:peach fg:surface0)"

[git_state]
style = "bold peach"

[git_status]
conflicted = "󱐋"
deleted = " "
format = "[$ahead_behind $all_status](bold bg:peach fg:surface0)[](fg:peach)[-](surface2)"
modified = " "
renamed = " "
staged = "󱊽"
stashed = " "
up_to_date = " 󰓦"

[golang]
format = "[](fg:sapphire)[$symbol($version)](bold bg:sapphire fg:surface0)[](fg:sapphire)[-](surface2)"
symbol = " "

[jobs]
format = "[](fg:subtext1)[$symbol$number](bold bg:subtext1 fg:surface0)[](fg:subtext1)[-](surface2)"
number_threshold = 1
symbol = " "

[nodejs]
format = "[](fg:green)[$symbol($version)](bold bg:green fg:surface0)[](fg:green)[-](surface2)"
symbol = "󰎙 "

[os]
disabled = true
format = "[](fg:overlay2)[$symbol](bg:overlay2 fg:surface0)[](fg:overlay2)[-](surface2)"

[os.symbols]
Android = " "
Arch = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
NixOS = " "
Raspbian = " "
Ubuntu = " "
Windows = "󰍲 "

[palettes.catppuccin_macchiato]
base = "#24273a"
blue = "#8aadf4"
crust = "#181926"
flamingo = "#f0c6c6"
green = "#a6da95"
lavender = "#b7bdf8"
mantle = "#1e2030"
maroon = "#ee99a0"
mauve = "#c6a0f6"
overlay0 = "#6e738d"
overlay1 = "#8087a2"
overlay2 = "#939ab7"
peach = "#f5a97f"
pink = "#f5bde6"
red = "#ed8796"
rosewater = "#f4dbd6"
sapphire = "#7dc4e4"
sky = "#91d7e3"
subtext0 = "#a5adcb"
subtext1 = "#b8c0e0"
surface0 = "#363a4f"
surface1 = "#494d64"
surface2 = "#5b6078"
teal = "#8bd5ca"
text = "#cad3f5"
yellow = "#eed49f"

[python]
format = "[](fg:yellow)[$symbol$pyenv_prefix($version )(($virtualenv))](bold bg:yellow fg:surface0)[](fg:yellow)[-](surface2)"
symbol = " "

[rust]
format = "[](fg:mauve)[$symbol($version)](bold bg:mauve fg:surface0)[](fg:mauve)[-](surface2)"
symbol = " "

[status]
disabled = false
format = "[](fg:red)[ $status](bold bg:red fg:surface0)[](fg:red)[-](surface2)"

[time]
disabled = false
format = "[](fg:rosewater)[ $time](bold bg:rosewater fg:surface0)[](fg:rosewater)[-](surface2)"
time_format = "%R"

[username]
format = "[](fg:red)[ $user](bold bg:red fg:surface0)[](fg:red)[-](surface2)"
